large_objects = [
    'Knife',
    'SinkBasin',
    'Arm Chair',
    'Bathtub Basin',
    'Bed',
    'Cabinet',
    'Cart',
    'Coffee Machine',
    'Coffee Table',
    'Counter Top',
    'Desk',
    'Dining Table',
    'Drawer',
    'Dresser',
    'Fridge',
    'Garbage Can',
    'Microwave',
    'Ottoman',
    'Safe',
    'Shelf',
    'Side Table',
    'Sofa',
    'Stove Burner',
    'TV Stand',
    'Toilet',
    'None'
]

ai2thor_large_objects = [
    'Knife',
    'SinkBasin',
    'ArmChair',
    'BathtubBasin',
    'Bed',
    'Cabinet',
    'Cart',
    'CoffeeMachine',
    'CoffeeTable',
    'CounterTop',
    'Desk',
    'DiningTable',
    'Drawer',
    'Dresser',
    'Fridge',
    'GarbageCan',
    'Microwave',
    'Ottoman',
    'Safe',
    'Shelf',
    'SideTable',
    'Sofa',
    'StoveBurner',
    'TVStand',
    'Toilet',
    'None'
]